CREATE TABLE IF NOT EXISTS post (
    no BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    views INT DEFAULT 0
);
